### ISSUE TITLE
Massive FPS decrease > skills command

### ISSUE THREAD

**Issue by MarkinhosMLP** [Archy-X/AureliumSkills#37] opened 2021-07-03 07:35 UTC
**Server Version and Software**
e.g. Paper 1.17

**Description**
For some players in my server, and also myself when using the command /skills we have a significant fps decrease, causing massive lags, but for some reason it does not affect some other players.

**How To Reproduce**
1.  Using /skills as i said

**Expected behavior**
Well... i expected the normal

**Actual behavior**
What is actually meant to happen aka showing the skills normally

**Screenshots**
![2021-07-03_04 34 19](https://user-images.githubusercontent.com/47507632/124346943-03d9c180-dbb8-11eb-8972-cf4cd194919f.png)
![2021-07-03_04 34 26](https://user-images.githubusercontent.com/47507632/124346945-050aee80-dbb8-11eb-8633-35b13744d6f0.png)
![2021-07-03_04 34 30](https://user-images.githubusercontent.com/47507632/124346946-050aee80-dbb8-11eb-8f32-17a4afa8371d.png)

**Comment by MarkinhosMLP** [comment] 2021-07-03 07:36
Uploading Minecraft_ 1.17 - Singleplayer 2021-06-21 03-37-57.mp4…

**Comment by Archy-X** [comment] 2021-07-03 21:09
Since it only affects some players, it is probably a client issue or hardware not being good enough. I have never experienced an FPS decrease when opening the menu so I don't know why that would happen. If you have more info about specifically the hardware/client version of the players who do experience it I would be happy to look into it more.

**Comment by MarkinhosMLP** [comment] 2021-07-09 23:16
the client version for the server is only 1.17 and about the hardware idk, because there are some people with weak computers which can use it with no fps decrease, and others having fps decrease... for example myself, i have a gamer computer and with or without resource pack i have this massive fps decrease... so i have no idea

**Comment by Archy-X** [comment] 2021-09-29 02:28
Closing because I'm unable to reproduce, reopen if you have additional information

**Closed by Archy-X** 2021-09-29 02:28 UTC
Labels: resolution: cannot reproduce
