### ISSUE TITLE
%aureliumskills_power% placeholder issue

### ISSUE THREAD

**Issue by liquidman228** [Archy-X/AureliumSkills#135] opened 2022-09-11 19:49 UTC
### Server software and version

Paper 1.19.2

### Expected behavior

Returning as 0 for the new player, until the player level-up some skills

### Actual behavior

It actually returns as 0 for the new player, but if he rejoin the server, it will show the value of 15 (and after that levels-up normally - 16, 17 and further)

### How to reproduce

Join the server as a new player, rejoin and parse the placeholder with a scoreboard or PAPI command

### Additional information

I want to use this placeholder to allow players to unlock some other aspects of the server. But this issue making them unlock things earlier than it should

### Agreements

- [X] I am running the latest version of Aurelium Skills
- [X] I am not using an unsupported server software (https://wiki.aurelium.dev/skills/other/incompatibilities)
- [X] My version of Minecraft is supported by Aurelium Skills

**Comment by Archy-X** [comment] 2022-09-11 19:51
The intended behavior is for the placeholder to return 15 for new players since players have level 1 skills starting out.

**Comment by liquidman228** [comment] 2022-09-11 20:35
> The intended behavior is for the placeholder to return 15 for new players since players have level 1 skills starting out.

Sorry, my bad, didn't think about that. But it will be great if we had a placeholder that behaves like i described in "expected behavior"

**Comment by Archy-X** [comment] 2022-09-11 20:42
I made a commit that should make the placeholder consistent in the next update

**Comment by TUCAOEVER** [comment] 2022-11-11 08:08
Any progress?

**Comment by Archy-X** [comment] 2022-11-11 14:13
This should be already fixed in the released Beta 1.3.10 update

**Comment by TUCAOEVER** [comment] 2022-11-11 14:13
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed** 2023-01-16 07:22 UTC
Labels: type: bug
